### ISSUE TITLE
setuptools-odoo is not adding non .py files

### ISSUE THREAD

**Issue by warp10** [acsone/setuptools-odoo#34]
setuptools-odoo 2.4.1 (installed via pip from PyPI) builds wheels with .py files and standard eggs files only, ignoring xml files, static/* and whatnot. It works great on OCA repos though, so I'm wondering if rather than a setuptools-odoo bug it's just me missing something out. I noticed this behavior on repos for versions 11, 10 and 8.

Steps to reproduce:
1. clone a repo with odoo addons for either Odoo 8, 10 or 11
2. run setuptools-odoo-make-default to create the setup directory
3. run python setup.py bdist_wheel on one of the addons
4. a proper wheelfile is generated, but it lacks all non .py files

I don't see any relevant warning or error message in setuptools logs, and the repo structure follows CA guidelines. Also, the .git directory is present. I can't really call this a bug as it works great on a random OCA repo, but I can't figure out what's missing or wrong in my process. Any clue?

**Comment by sbidoul** [comment]
automatic detection of such files relies on setuptools_scm's git file finder. Could it be the files you want to include are not yet committed in git?

**Comment by warp10** [comment]
Not indeed. All of them were actually downloaded by the clone step, so they are already tracked by git.

**Comment by sbidoul** [comment]
That's strange. Is this a public repo?

**Comment by warp10** [comment]
It isn't, but I can grant you access to another repo for version 11 where I have the same issue. If you share an SSH key I will gladly add it to the repo

**Comment by sbidoul** [comment]
https://github.com/sbidoul.keys

**Comment by warp10** [comment]
Thank you Stéphane. Couldn't add the first key (Bitbucket says it has been already added elsewhere) but I added the second one.

You can now git clone git@bitbucket.org:openforceit/event.git, branch 11.0

**Comment by sbidoul** [comment]
Hm, it does not work. Can you please remove that key from your repo and authorize my bitbucket user instead? https://bitbucket.org/stephane_bidoul/

**Comment by warp10** [comment]
Done

**Comment by eLBati** [comment]
@warp10 I vauely remember a similar problem. Could you check if using `setuptools-git==1.1` the problem still occurs?

**Comment by warp10** [comment]
@eLBati spot on. @sbidoul I run multiple tests on the repo for Odoo 11 I granted you access to:
- `setuptools-git` not installed: only .py files are added
- `setuptools-git==1.0`: all files properly added
- `setuptools-git==1.1`: all files properly added
- `setuptoots-git==1.2`: no files added

**Comment by warp10** [comment]
@sbidoul FYI: I run a git bisect on setuptools-git, it looks like the change the breaks setuptools-odoo is this one:
https://github.com/msabramo/setuptools-git/commit/4885c6575b7a5b7c989450829fb15078fddab34d#diff-f7fc24542b115c5af29585224e83df81

**Comment by sbidoul** [comment]
setuptools-git 1.2 is known to be broken indeed: https://github.com/msabramo/setuptools-git/pull/13.
It is also unmaintained. 

Nowadays setuptools-odoo depends on setuptools_scm for git file detection.

I think the real issue in your case is that the `setup` directory is not in git, so setuptools_scm does not detect the files since `odoo/addons` is not in git.

Can you try after running `setuptools-odoo-make-default --clean -d . --commit` at the root of your repo?

**Comment by warp10** [comment]
@sbidoul Indeed the untracked `setup/`directory was the issue. `--commit` makes everything work great without `setuptools-git`. Thanks a lot!
